In [3]:
import numpy as np

Q1. Create a NumPy array of integers from 1 to 10.

In [ ]:
arr12=np.arange(1,11)

In [ ]:
arr12

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Q2. Create a 2x3 NumPy array filled with zeros.

In [ ]:
a=np.zeros((2,3))

In [ ]:
a

array([[0., 0., 0.],
       [0., 0., 0.]])

Q3. Create a NumPy array of even numbers from 2 to 20.

In [ ]:
arr10=np.arange(2,21,2)

In [ ]:
arr10

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

Q4. Given two NumPy arrays, arr1 = np.array ([1, 2, 3]) and arr2 = np.array ([4,
5, 6]), perform element-wise addition, subtraction, multiplication, and
division between the two arrays.


In [ ]:
arr1 = np.array ([1, 2, 3])
arr1

array([1, 2, 3])

In [ ]:
arr2 = np.array ([4, 5, 6])
arr2

array([4, 5, 6])

In [ ]:
arr3= arr1+arr2
arr3

array([5, 7, 9])

In [ ]:
arr4=arr1-arr2
arr4

array([-3, -3, -3])

In [ ]:
arr5=arr1*arr2
arr5

array([ 4, 10, 18])

In [ ]:
arr6=arr1/arr2
arr6

array([0.25, 0.4 , 0.5 ])

Q5. Compute the mean, median, and standard deviation of a NumPy array
containing 100 random numbers.


In [ ]:
arr20=np.random.randint(1,101,100)

In [ ]:
arr20

array([  9,  57,   7,  60,  54,  93,  61,  50,  89,   9,  10,  16,  77,
        66,  21, 100,  70,   4,  11,  53,  36,  72,  57,  32,  67,  76,
        58, 100,   8,  67,  13,  93,  18,  93,  94,  48,  52,   7,  85,
        68,  84,  39,  12,  68,  51,  64,  74,  44,  84,  26,  27,   4,
        88,  69,  25,  50,  54,  75,  26,  90,  39,  28,   7,  65,  42,
        11,  76,  62,  88,  51,  99,  35,  77,  59,  24,  61,  48,  98,
        88,  31,  39,  63,  75,  48,  63,  46,   8,  42,  33,  33,  40,
        77,  23,  85, 100, 100,  42,  28,  21,  11])

In [ ]:
arr20.mean()

51.81

In [ ]:
arr20.sort()

In [ ]:
arr20

array([  4,   4,   7,   7,   7,   8,   8,   9,   9,  10,  11,  11,  11,
        12,  13,  16,  18,  21,  21,  23,  24,  25,  26,  26,  27,  28,
        28,  31,  32,  33,  33,  35,  36,  39,  39,  39,  40,  42,  42,
        42,  44,  46,  48,  48,  48,  50,  50,  51,  51,  52,  53,  54,
        54,  57,  57,  58,  59,  60,  61,  61,  62,  63,  63,  64,  65,
        66,  67,  67,  68,  68,  69,  70,  72,  74,  75,  75,  76,  76,
        77,  77,  77,  84,  84,  85,  85,  88,  88,  88,  89,  90,  93,
        93,  93,  94,  98,  99, 100, 100, 100, 100])

In [ ]:
median=(arr20[49]+[50])/2
median

array([51.])

In [ ]:
SD=arr20.std()
SD

28.33573538837487

Q6. Reshape a 1D NumPy array of 12 random elements into a 2D array with a
shape of (3, 4).

In [ ]:
arr23=np.random.randint(1,50,12)
arr23

array([30,  5, 25, 20,  7, 21, 15, 23, 23, 20,  6, 24])

In [ ]:
arr23.reshape(3,4)

array([[30,  5, 25, 20],
       [ 7, 21, 15, 23],
       [23, 20,  6, 24]])

Q7. Given a NumPy array arr = np.array([1, 2, 3, 4, 5]), square each element in  the array using NumPy functions.


In [ ]:
arr=np.array([1,2,3,4,5])

In [ ]:
np.square(arr)

array([ 1,  4,  9, 16, 25])

Q8. Create a 5x5 identity matrix using NumPy.


In [ ]:
np.eye(5,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

Q9. Calculate the dot product of two NumPy arrays, a = np.array([1, 2, 3]) and  b = np.array([4, 5, 6]).

In [ ]:
a=np.array([1,2,3])
b=np.array([4,5,6])

In [ ]:
a.dot(b)

32

Q10. Find the index of the maximum value and the index of the minimum value  in a NumPy array.

In [ ]:
arr5=np.random.randint(10,75,15)

In [ ]:
arr5

array([62, 69, 34, 48, 14, 57, 49, 42, 58, 26, 72, 66, 35, 30, 53])

In [ ]:
arr5.argmax()

10

In [ ]:
arr5.argmin()

4

Q11. Concatenate two random NumPy arrays horizontally and vertically.


In [ ]:
a=np.zeros((4,4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
b=np.ones((4,4))
b

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
c=np.concatenate((a,b))
print('Vertical concantation-\n',c)


Vertical concantation-
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
d=np.concatenate((a,b),axis=1)
print('horizontal concantation-\n',d)

horizontal concantation-
 [[0. 0. 0. 0. 1. 1. 1. 1.]
 [0. 0. 0. 0. 1. 1. 1. 1.]
 [0. 0. 0. 0. 1. 1. 1. 1.]
 [0. 0. 0. 0. 1. 1. 1. 1.]]


Q12. Given a 2D NumPy array, calculate the sum of each row and each column  separately.

In [ ]:
arr=np.arange(1,17).reshape(4,4)
print(arr)
print('Sum of each column is',np.sum(arr,axis=0))
print('Sum of each column is',np.sum(arr,axis=1))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Sum of each column is [28 32 36 40]
Sum of each column is [10 26 42 58]


Q13. Find the common elements between two NumPy arrays.

In [ ]:
a=np.array([[1,10],[12,8],[1,0]])
b=np.array([[3,1],[5,12],[6,0]])
c=np.intersect1d(a,b)
print('The common elements are',c)

The common elements are [ 0  1 12]


Q14. Replace all negative values in a NumPy array with zeros.


In [ ]:
a=np.array([4,5,6,-7,-8,-9])
a[a<0]=0
a

array([4, 5, 6, 0, 0, 0])

Q15. Create a NumPy array with random integers between 1 and 100 and then  sort it in ascending order.

In [ ]:
arr8=np.random.randint(1,101,100)
arr8

array([ 10,  25,  62,   9,  67,  63,  19,  60,  91,  89, 100,  80,  33,
        27,  56,  46,  11,  64,  46,  42,  29,  13,  46,  93,  27,  18,
        19,  75,  10,  29,  49,  28,  94,  23,  73,  88,  22,  50,  34,
        17,  14,  57,  41,  34,  43,  32,   2,  56,  29,  26,  28,  24,
        12,  46,  86,   8,  70,  49,  56,  47,  32,  29,  47,  54,  83,
        48,  57,  91,  21,  10,  45,  47,  59,  26,   3,  48,  68,  15,
        38,  92,  30,  28,  20,  70,  89,  49,  84,  82,  93,  52,  18,
        22,  18,  78,  93,  32,  97,  87,  44,  24])

In [ ]:
arr8.sort()
arr8

array([  2,   3,   8,   9,  10,  10,  10,  11,  12,  13,  14,  15,  17,
        18,  18,  18,  19,  19,  20,  21,  22,  22,  23,  24,  24,  25,
        26,  26,  27,  27,  28,  28,  28,  29,  29,  29,  29,  30,  32,
        32,  32,  33,  34,  34,  38,  41,  42,  43,  44,  45,  46,  46,
        46,  46,  47,  47,  47,  48,  48,  49,  49,  49,  50,  52,  54,
        56,  56,  56,  57,  57,  59,  60,  62,  63,  64,  67,  68,  70,
        70,  73,  75,  78,  80,  82,  83,  84,  86,  87,  88,  89,  89,
        91,  91,  92,  93,  93,  93,  94,  97, 100])

Q16. Calculate the element-wise absolute difference between two NumPy arrays.


In [ ]:
a=np.array([1,2,3,4,5])
b=np.array([6,7,8,9,10])
c=np.absolute(a-b)
print('The element-wise absolute difference between two NumPy arrays ',c)


The element-wise absolute difference between two NumPy arrays  [5 5 5 5 5]


Q17. Given a 2D NumPy array, extract the first row and the last column.

In [ ]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
a=arr[0]
b=arr[:,[-1]]
print('First row is\n',a)
print('Last column is\n',b)

First row is
 [1 2 3]
Last column is
 [[3]
 [6]
 [9]]


Q18. Slice a 1D NumPy array to get every other element.


In [ ]:
a=np.array([1,2,3,4,5])
b=a[0:len(a)+1]
print(b)

[1 2 3 4 5]


Q19. Given a 2D NumPy array, extract a subarray consisting of the central 2x2  elements.


In [4]:
arr13=np.array([[10,1,14,16,18,20],[22,24,26,28,30,32],[34,36,38,40,42,44],[46,48,50,52,54,56],[58,60,62,64,66,68],[70,72,74,76,78,80]])
arr13

array([[10,  1, 14, 16, 18, 20],
       [22, 24, 26, 28, 30, 32],
       [34, 36, 38, 40, 42, 44],
       [46, 48, 50, 52, 54, 56],
       [58, 60, 62, 64, 66, 68],
       [70, 72, 74, 76, 78, 80]])

In [5]:
x=arr13[2:4,[2,3]]
print(x)

[[38 40]
 [50 52]]


Q20. Reverse a 1D NumPy array using slicing.


In [6]:
a=np.array([1,2,3,4,5])
x=a[::-1]
x

array([5, 4, 3, 2, 1])